=== ops4j/org.ops4j.xvisitor/xvisitor-itest/src/main/resources/xsd/ConceptSpace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://simf.omg.org/ConceptSpace" elementFormDefault="unqualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://simf.omg.org/ConceptSpace">

    <complexType name="Element">
    	<sequence>
    		<element name="uri" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="commonName" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="definition" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="version" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="ownedConcepts" type="tns:Element"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>
    
   <complexType name="Document">
    	<sequence>
		    <element name="conceptSpace" type="tns:Element" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
   </complexType>
   
   <element name="document" type="tns:Document"></element>

    <complexType name="Reference">
    	<complexContent>
    		<extension base="tns:Element">
    			<sequence>
    				<element name="referencedElement" type="string" maxOccurs="1" minOccurs="1"></element>
    				<element name="referencedElementVersion" type="string" maxOccurs="1" minOccurs="1"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="Constraint">
    	<complexContent>
    		<extension base="tns:Element">
    			<sequence>
    				<element name="constraintExpression" type="string" maxOccurs="1" minOccurs="1"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="Refinement">
    	<complexContent>
    		<extension base="tns:Element">
    			<sequence>
    				<element name="parent" type="string" maxOccurs="1" minOccurs="1"></element>
    				<element name="child" type="string" maxOccurs="1" minOccurs="1"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

</schema>

=== ops4j/org.ops4j.xvisitor/xvisitor-itest/src/test/resources/test-data/ConceptSpace1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:document xmlns:tns="http://simf.omg.org/ConceptSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://simf.omg.org/ConceptSpace ConceptSpace.xsd ">
  <conceptSpace>
    <uri>uri1</uri>
    <commonName>commonName1</commonName>
    <definition>definition1</definition>
    <version>version1</version>
  </conceptSpace>
  <conceptSpace>
    <uri>uri2</uri>
    <commonName>commonName2</commonName>
    <definition>definition2</definition>
    <version>version2</version>
  </conceptSpace>
  <conceptSpace>
    <uri>uri3</uri>
    <commonName>commonName3</commonName>
    <definition>definition3</definition>
    <version>version3</version>
  </conceptSpace>
</tns:document>
